use_default_settings: true

server:
  bind_address: "0.0.0.0"
  port: 8080
  secret_key: "ultrasecretkeychangeitforproduction"
  limiter: false
  image_proxy: true

search:
  formats:
    - html
    - json
